"""add generator FKs to routine_inspections

Revision ID: 7c4d1e88b5a2
Revises: 2a338aefef5c
Create Date: 2026-09-04 09:30:00.000000

Links each generator section of a routine inspection to a registered unit, so
the report renders the unit's real identity instead of a free-text serial, and
so "every inspection for this unit" is a plain join.

Both columns are nullable and stay NULL for every inspection recorded before
the asset register existed. The `data` JSONB is untouched — historical payloads
keep their `serialNumber` exactly as captured, and the read side falls back to
it when there is no link.

Hand-written rather than autogenerated, for the same reason as 2a338aefef5c:
autogenerate against this database also sweeps up the pre-existing baseline
drift documented in the baseline migration.

⚠ LOCAL ONLY for now. Pending for the Live branch migration.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c4d1e88b5a2"
down_revision: Union[str, Sequence[str], None] = "2a338aefef5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "routine_inspections",
        sa.Column("gen1_generator_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "routine_inspections",
        sa.Column("gen2_generator_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        "fk_routine_inspections_gen1_generator_id",
        "routine_inspections",
        "generators",
        ["gen1_generator_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_routine_inspections_gen2_generator_id",
        "routine_inspections",
        "generators",
        ["gen2_generator_id"],
        ["id"],
    )
    # A unit's inspection history is read by generator, so index the way it is
    # queried. Partial on NOT NULL: pre-register rows are the majority for now
    # and are never the target of that lookup.
    op.create_index(
        "ix_routine_inspections_gen1_generator_id",
        "routine_inspections",
        ["gen1_generator_id"],
        postgresql_where=sa.text("gen1_generator_id IS NOT NULL"),
    )
    op.create_index(
        "ix_routine_inspections_gen2_generator_id",
        "routine_inspections",
        ["gen2_generator_id"],
        postgresql_where=sa.text("gen2_generator_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema.

    Only the links are lost. The inspection payloads were never rewritten, so
    every section still carries the `serialNumber` it was captured with.
    """
    op.drop_index(
        "ix_routine_inspections_gen2_generator_id",
        table_name="routine_inspections",
        postgresql_where=sa.text("gen2_generator_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_routine_inspections_gen1_generator_id",
        table_name="routine_inspections",
        postgresql_where=sa.text("gen1_generator_id IS NOT NULL"),
    )
    op.drop_constraint(
        "fk_routine_inspections_gen2_generator_id",
        "routine_inspections",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_routine_inspections_gen1_generator_id",
        "routine_inspections",
        type_="foreignkey",
    )
    op.drop_column("routine_inspections", "gen2_generator_id")
    op.drop_column("routine_inspections", "gen1_generator_id")
