"""add finance-technician workflow

Revision ID: b7f21c9e40aa
Revises: 97f73cf72ab8
Create Date: 2026-08-18 12:00:00.000000

Phase 1 of FINANCE_TECHNICIAN_IMPLEMENTATION_PLAN.md, implementing the data
model in docs/FieldCore_Finance_Technician_Workflow_Spec.md §4.

WRITTEN BY HAND, NOT AUTOGENERATED. `--autogenerate` against the live DB
surfaces the same broad pre-existing drift the baseline migration's docstring
documents (GIST index churn on technicians/sites geometry columns, VARCHAR vs
Enum and NOT NULL mismatches across a dozen unrelated tables). None of it
belongs to this change and at least one item would actively break working
proximity queries, so this file contains only the new objects.

EVERY OPERATION HERE IS ADDITIVE. Six new tables, one nullable column, one
enum label. There is no backfill, no NOT NULL added to an existing table, no
type change to an existing column, and no write to any existing row — nothing
that can affect the usability of the production database.

Every enum here is a NATIVE Postgres type whose labels are member NAMES
(uppercase), because that is what SQLModel generates and what the rest of this
schema already uses — `sites.region` is a real `region` type holding 'GAUTENG',
'KZN', and so on, and `users.role` is `userrole`.

An earlier revision of this file created these columns as VARCHAR instead. That
came from inspecting column types via `str(col.type)`, which renders `sa.Enum`
as `VARCHAR(n)` when no dialect is bound — compile against the postgres dialect
and the same column renders as `fundsrequeststatus`. The app still worked
(SQLAlchemy writes the label into a varchar quite happily), but the models and
the schema disagreed, so `--autogenerate` wanted to ALTER all six columns on
every future run. That is precisely the drift the baseline migration warns
about, so it is fixed here rather than layered over.

`technicians.region` reuses the existing `region` type via create_type=False;
emitting CREATE TYPE for it would fail because sites.region already created it.

Adding FINANCE to `userrole` needs `ALTER TYPE ... ADD VALUE` (uppercase
label), which cannot run inside a transaction — hence the autocommit_block,
same as the reporttype migration.

DEPLOY NOTE: as with the reporttype migration, applying this to the live DB is
a deliberate deploy-time step requiring its own explicit go-ahead, not a side
effect of merging. Verify against production first that `technicians` has no
existing `region` column (the drift noted in the baseline included altered
columns on that table).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7f21c9e40aa"
down_revision: Union[str, Sequence[str], None] = "97f73cf72ab8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ── UserRole.FINANCE ──────────────────────────────────────────────────
    # Grants sight of the Finance Dashboard. Authority over a chain stage is a
    # funds_capabilities row, never this role.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'FINANCE'")

    # ── generators ────────────────────────────────────────────────────────
    # Forward-only. Existing diesel report JSON keeps its free-text gen_no;
    # scripts/seed_generators.py creates rows matching those units so the
    # dashboard can resolve legacy fills by (site_id, gen_no) without a rewrite.
    op.create_table(
        "generators",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("gen_no", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # Partial unique throughout this migration: BaseDB.soft_delete only sets
    # deleted_at, so a soft-deleted row must not permanently occupy a unique slot.
    op.create_index(
        "uq_generators_site_gen_no",
        "generators",
        ["site_id", "gen_no"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ── funds_capabilities ────────────────────────────────────────────────
    # Who may act on which stage of the chain. Rows, not enum values, because
    # one person can hold several capabilities at once (spec §2 has a single
    # individual as both fallback approver and releaser).
    op.create_table(
        "funds_capabilities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "capability",
            sa.Enum("APPROVE", "LOAD", "RELEASE", "FINANCE_LEAD", name="fundscapability"),
            nullable=False,
        ),
        sa.Column("is_fallback", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_funds_capabilities_user_capability",
        "funds_capabilities",
        ["user_id", "capability"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_funds_capabilities_capability",
        "funds_capabilities",
        ["capability"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )

    # ── funds_requests ────────────────────────────────────────────────────
    # Single ledger with a type discriminator (resolves spec §7 Q5).
    op.create_table(
        "funds_requests",
        sa.Column("technician_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "WEEKLY_TRIP", "GENERATOR_REFUEL", "MISC", name="fundsrequesttype"
            ),
            nullable=False,
        ),
        # Weekly trip inputs. Stored for audit beside the submitted amount; the
        # external calculator stays the source of truth (spec §3.1).
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("vehicle_efficiency_l_per_100km", sa.Float(), nullable=True),
        # Generator refuel inputs.
        sa.Column("site_id", sa.Uuid(), nullable=True),
        sa.Column("generator_id", sa.Uuid(), nullable=True),
        sa.Column("requested_liters", sa.Float(), nullable=True),
        sa.Column("gen_runtime_hours", sa.Float(), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "LOADED",
                "RELEASED",
                "REJECTED",
                "CANCELLED",
                name="fundsrequeststatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("NORMAL", "HIGH", name="fundspriority"), nullable=False
        ),
        # Money is NUMERIC, never double precision. These are the first exact
        # money columns in the schema; legacy diesel amounts live as floats
        # inside report JSON and must never be summed into these without an
        # explicit conversion.
        sa.Column("requested_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        # Always manually entered per request and stored here for audit
        # (spec §3.1 rule, §4) — never derived from a lookup, a location or a
        # date. 4 dp because pump prices are quoted to the tenth of a cent.
        sa.Column(
            "diesel_price_per_liter", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        # Friday→Thursday SAST bounds, snapshotted at creation.
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["technician_id"], ["technicians.id"]),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"]),
        sa.ForeignKeyConstraint(["generator_id"], ["generators.id"]),
        sa.ForeignKeyConstraint(["rejected_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_funds_requests_technician_period",
        "funds_requests",
        ["technician_id", "period_start"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_funds_requests_status",
        "funds_requests",
        ["status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_funds_requests_type_status",
        "funds_requests",
        ["type", "status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_funds_requests_site",
        "funds_requests",
        ["site_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ── disbursements ─────────────────────────────────────────────────────
    # Approval alone never releases funds (spec §6) — the three acts are
    # recorded separately, each with its own identity and timestamp.
    op.create_table(
        "disbursements",
        sa.Column("funds_request_id", sa.Uuid(), nullable=False),
        sa.Column("amount_issued", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_fallback_approval", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("loaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("loaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["funds_request_id"], ["funds_requests.id"]),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["loaded_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["released_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_disbursements_funds_request",
        "disbursements",
        ["funds_request_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_disbursements_released_at",
        "disbursements",
        ["released_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ── reconciliations ───────────────────────────────────────────────────
    # One per disbursement (spec §4), separate from the diesel report: that is
    # operational proof, this is financial proof.
    op.create_table(
        "reconciliations",
        sa.Column("disbursement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "SUBMITTED", "APPROVED", "REJECTED", name="reconciliationstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "total_used",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "outstanding_balance",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default="0",
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finance_approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("finance_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["disbursement_id"], ["disbursements.id"]),
        sa.ForeignKeyConstraint(["finance_approved_by_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_reconciliations_disbursement",
        "reconciliations",
        ["disbursement_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_reconciliations_status",
        "reconciliations",
        ["status"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_reconciliations_period",
        "reconciliations",
        ["period_start"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ── reconciliation_lines ──────────────────────────────────────────────
    op.create_table(
        "reconciliation_lines",
        sa.Column("reconciliation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("FUEL", "TOLL", "MISC", name="expensecategory"),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("incurred_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        # Supabase Storage path, via the existing signed-upload flow. Nullable so
        # a line can be captured before its photo finishes uploading on a poor
        # connection; the service requires one on every line before submission.
        sa.Column("slip_file_path", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["reconciliation_id"], ["reconciliations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reconciliation_lines_reconciliation",
        "reconciliation_lines",
        ["reconciliation_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ── technicians.region ────────────────────────────────────────────────
    # Nullable, no backfill. Spec §4 wants a region on the technician profile
    # for dashboard grouping, but populating it would write to every existing
    # row. VARCHAR(13) matches sites.region, which SQLModel generates from the
    # same Region StrEnum ('kwazulu-natal' being the longest value). Rows left
    # NULL group under "Unassigned" on the dashboard.
    op.add_column(
        "technicians",
        sa.Column(
            "region",
            # create_type=False: the `region` enum already exists, created with
            # sites.region. Letting SQLAlchemy emit CREATE TYPE here would fail.
            postgresql.ENUM(name="region", create_type=False),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema.

    Drops only what upgrade() created, youngest first for the FK chain. The
    UserRole.FINANCE label is deliberately left in place: Postgres has no
    `ALTER TYPE ... DROP VALUE`, and removing a label means recreating the type
    along with every column and index using it — the same reasoning as the
    reporttype migration's no-op downgrade.
    """
    op.drop_column("technicians", "region")

    op.drop_index(
        "ix_reconciliation_lines_reconciliation",
        table_name="reconciliation_lines",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("reconciliation_lines")

    op.drop_index(
        "ix_reconciliations_period",
        table_name="reconciliations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_reconciliations_status",
        table_name="reconciliations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_reconciliations_disbursement",
        table_name="reconciliations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("reconciliations")

    op.drop_index(
        "ix_disbursements_released_at",
        table_name="disbursements",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_disbursements_funds_request",
        table_name="disbursements",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("disbursements")

    for name in (
        "ix_funds_requests_site",
        "ix_funds_requests_type_status",
        "ix_funds_requests_status",
        "ix_funds_requests_technician_period",
    ):
        op.drop_index(
            name, table_name="funds_requests", postgresql_where=sa.text("deleted_at IS NULL")
        )
    op.drop_table("funds_requests")

    op.drop_index(
        "ix_funds_capabilities_capability",
        table_name="funds_capabilities",
        postgresql_where=sa.text("deleted_at IS NULL AND is_active"),
    )
    op.drop_index(
        "uq_funds_capabilities_user_capability",
        table_name="funds_capabilities",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("funds_capabilities")

    op.drop_index(
        "uq_generators_site_gen_no",
        table_name="generators",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("generators")

    # drop_table does not drop the enum types create_table brought into being,
    # so a downgrade/upgrade cycle would fail on "type already exists" without
    # this. The `region` type is deliberately NOT dropped — it predates this
    # migration and sites.region still uses it.
    for enum_name in (
        "fundscapability",
        "fundsrequesttype",
        "fundsrequeststatus",
        "fundspriority",
        "reconciliationstatus",
        "expensecategory",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
