-- Fix incident severity values to UPPERCASE to match SQLAlchemy enum name-based mapping.
-- Migration 0016 added the column with DEFAULT 'minor' and a CHECK constraint for lowercase.
-- SQLAlchemy resolves Python enum members by their NAME (e.g. MINOR, MAJOR) when reading
-- rows back, so the DB values must be uppercase to match.

-- 1. Drop the old lowercase check constraint (name is auto-generated by Postgres)
ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidents_severity_check;

-- 2. Uppercase all existing severity values
UPDATE incidents
SET severity = UPPER(severity)
WHERE severity IN ('critical', 'major', 'minor', 'query');

-- 3. Change the column default to uppercase
ALTER TABLE incidents ALTER COLUMN severity SET DEFAULT 'MINOR';

-- 4. Recreate the check constraint with uppercase values
ALTER TABLE incidents
    ADD CONSTRAINT incidents_severity_check
    CHECK (severity IN ('CRITICAL', 'MAJOR', 'MINOR', 'QUERY'));

-- 5. Rebuild the index (drop + recreate to keep it consistent)
DROP INDEX IF EXISTS idx_incidents_severity;
CREATE INDEX idx_incidents_severity ON incidents(severity) WHERE deleted_at IS NULL;
